### ISSUE TITLE
ভাই ডেপ্লয় করা একটা ডেমো লিঙ্ক দেন রিপো তে, তাহলে এক্সপ্লোর করতে ভালো হবে। 

### ISSUE THREAD

**Issue by nomandhoni-cs** [sr-tamim/nextjs-boilerplate#2]

**Comment by sr-tamim** [comment]
@nomandhoni-cs ভাই, এটা তো just boilerplate code... এখানে explore করার মত তেমন কিছুই নাই আসলে

**Comment by nomandhoni-cs** [comment]
UI and Language switching ta kivabe kaj kore seta dekhle valo hoito na?
